### ISSUE TITLE
0.3.0 Epic

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/content-kit-editor#13]
* [x] Implement a serializer for the post AT to a serialized format
* [x] Package for distribution a DOM renderer (https://github.com/bustlelabs/mobiledoc-dom-renderer)
* [x] Package for distribution a HTML renderer (https://github.com/bustlelabs/mobiledoc-html-renderer)
* [x] Handle section modification, removal, addition en-masse (edits across sections)
* [x] Don't create a section element during post render for editor
* [x] Pass serialized payload to the editor for use (https://github.com/bustlelabs/content-kit-editor/commit/06def745078c52e79744531a4aee266b4cd13229)
* [x] An inserted `<span>` or other ignorable element in the editor's HTML needs to be ignored properly so that you can delete to join two sections
* [x] write serializer tests
* [x] write acceptance tests against serializer output
* [x] parse the serialized format into the AT for the editor ( https://github.com/bustlelabs/content-kit-compiler/commit/0db07a6058e9af19657808b5f2d6fb9f8dd047aa )
* [x] `Editor#destroy` tears down listeners, cleans up after itself
* [x] Assert correct command and UI behaviors of markup commands: (https://github.com/bustlelabs/content-kit-editor/pull/17)
  * [x] bold
  * [x] italic
  * [x] link
* [ ] Assert correct command an UI behaviors for sections (these are all new section types)
  * [x] image (port image implementation to a card)
  * [x] embed (including embeds that hit the embed API for HTML) (port embed implementation to a card)
  * [ ] ~~display of available cards in ContentKit~~ punting this to the UI-focused work in 0.4.0
  * [x] quote
  * [x] headline
  * [x] subheadline
* [x] remove remaining memory-leaked event listeners (Tooltip adds a mouseover listener, e.g., and there are a few others) (https://github.com/bustlelabs/content-kit-editor/pull/18)
* [x] DOM renderer should know how to render a card
* [x] HTML renderer should know how to render a card (should use a new bag of hooks called `html`)

Stretch

* [ ] two-pass parse that avoids the previous-section and isGenerated nonsense
* [x] make post AT nodes a linked list
* [x] parse/rerender markers instead of sections
* [x] serializer should serialize null values as a blank text node
* [ ] IE 10 tests pass and demo works (blocked on lack of `input` event on contenteditable)

**Comment by mixonic** [comment]
Yay, going to ship a 0.3.0 after @bantic lands a patch improving deletion/enter support.

**Comment by mixonic** [comment]
Nah, going to wait until https://github.com/bustlelabs/content-kit-editor/pull/53 lands

**Comment by mixonic** [comment]
0.3.0 published!
