### ISSUE TITLE
0.5.0 Epic

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/content-kit-editor#148]
* [x] Styles should be removable or possibly just not present. This means the initial Ember addon should be published with the editing tools.
* [ ] Possibly a validation API, but more likely this can just be a walker API that hits the post or a completed mobiledoc.
* [x] support basic copy/paste #111

**Comment by bantic** [comment]
closing as 0.5.0 is released.
A validation/walker API will come in a different version.
