### ISSUE TITLE
0.4.0 Epic

### ISSUE THREAD

**Issue by mixonic** [bustlelabs/content-kit-editor#34]
* [ ] ~~Pass buttons to content-kit instances for the toolbar~~
* [x] Ship programmatic postEditor API (Add/document API on the editor instance that you can replace the current section with a card and payload) https://github.com/bustlelabs/content-kit-editor/pull/73
* [ ] ~~Mobiledoc could store meta data from the editor, ala "type". For example "listicle" or "listicle-style-one". this means an API on the editor. `postEditor.setMetadata(newData)` and `editor.post.metadata` to read~~ punting in favor of encouraging this kind of thing be stored on a proper model.
* [ ] Possibly a validation API, but more likely this can just be a walker API that hits the post or a completed mobiledoc
* [x] ~~Three levels of interaction.~~ https://github.com/bustlelabs/content-kit-editor/pull/82
  * ~~Text can be edited and sections created.~~
  * ~~Sections cannot be created/deleted, but text could be edited.~~
  * ~~Sections cannot be created/deleted, text cannot be edited ~~
* [x] Disable the cursor on an editor (disable contenteditable basically) https://github.com/bustlelabs/content-kit-editor/pull/82
* [x] Test using two content-kit editors on the same page
* [x] lists as text (making lists starting with a *) #86 #87 
* [ ] styles should be removable or possibly just not present.
* [x] Placeholder

**Comment by mixonic** [comment]
Closing this one, moving the open items to 0.5.0 which will come out in conjunction with the initial Ember addon
